UPDATE products SET ean = '3083681120189' WHERE brand = 'Bonduelle' AND product_name = 'Champignon Mushrooms' AND category = 'Canned Goods';
UPDATE products SET ean = '3083681003949' WHERE brand = 'Bonduelle' AND product_name = 'Chickpeas' AND category = 'Canned Goods';
UPDATE products SET ean = '3083681148619' WHERE brand = 'Bonduelle' AND product_name = 'Mixed Beans' AND category = 'Canned Goods';
UPDATE products SET ean = '3083680025881' WHERE brand = 'Bonduelle' AND product_name = 'Sweet Corn' AND category = 'Canned Goods';
UPDATE products SET ean = '5000157062673' WHERE brand = 'Heinz' AND product_name = 'Cream of Tomato Soup' AND category = 'Canned Goods';
UPDATE products SET ean = '5000157068743' WHERE brand = 'Heinz' AND product_name = 'Ravioli in Tomato Sauce' AND category = 'Canned Goods';
UPDATE products SET ean = '5000157006875' WHERE brand = 'Heinz' AND product_name = 'Spaghetti in Tomato Sauce' AND category = 'Canned Goods';
UPDATE products SET ean = '5900385012573' WHERE brand = 'Kotlin' AND product_name = 'Beans in Tomato Sauce' AND category = 'Canned Goods';
UPDATE products SET ean = '5901696000013' WHERE brand = 'Profi' AND product_name = 'Chicken Soup' AND category = 'Canned Goods';
UPDATE products SET ean = '5900783000424' WHERE brand = 'Pudliszki' AND product_name = 'Corned Beef' AND category = 'Canned Goods';
UPDATE products SET ean = '5900783004057' WHERE brand = 'Pudliszki' AND product_name = 'Vegetable Soup' AND category = 'Canned Goods';