-- Found 0 EANs in alcohol
-- Found 26 EANs in baby
-- Found 0 EANs in bread
-- Found 28 EANs in cereals
-- Found 21 EANs in chips
-- Found 0 EANs in dairy
-- Found 28 EANs in drinks
-- Found 0 EANs in instant
-- Found 0 EANs in meat
-- Found 0 EANs in sauces
-- Found 0 EANs in sweets
-- Found 28 EANs in zabka
-- MIGRATION: Populate products.ean column from pipeline comments
-- Generated by extract_eans.py
-- DO NOT EDIT MANUALLY - regenerate by running the script

Traceback (most recent call last):
  File "C:\Users\ericsocrat\Desktop\poland-food-db\extract_eans.py", line 97, in <module>
    main()
    ~~~~^^
  File "C:\Users\ericsocrat\Desktop\poland-food-db\extract_eans.py", line 68, in main
    print("-- \u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550")
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python314\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 3-75: character maps to <undefined>
