-- MIGRATION: Populate products.ean column from pipeline comments
-- Generated by extract_eans.py
-- DO NOT EDIT MANUALLY - regenerate by running the script

-- =============================================================================
-- Populate EAN codes extracted from pipeline SQL comments
-- =============================================================================

UPDATE products
SET ean = '5900552077718'
WHERE country = 'PL'
  AND brand = '4Move'
  AND product_name = '4Move Activevitamin';

UPDATE products
SET ean = '5900497017770'
WHERE country = 'PL'
  AND brand = '7UP'
  AND product_name = '7UP';

UPDATE products
SET ean = '8445290594334'
WHERE country = 'PL'
  AND brand = 'Bobo Frut'
  AND product_name = 'Bobo Frut Jabłko marchew';

UPDATE products
SET ean = '5900852068812'
WHERE country = 'PL'
  AND brand = 'BoboVita'
  AND product_name = 'BoboVita Delikatne jabłka z bananem';

UPDATE products
SET ean = '8591119253934'
WHERE country = 'PL'
  AND brand = 'BoboVita'
  AND product_name = 'BoboVita Jabłka i banana';

UPDATE products
SET ean = '5900852041129'
WHERE country = 'PL'
  AND brand = 'BoboVita'
  AND product_name = 'BoboVita Kaszka Mleczna 7 Zbóż Zbożowo-Jaglana Owocowa';

UPDATE products
SET ean = '5900852038112'
WHERE country = 'PL'
  AND brand = 'BoboVita'
  AND product_name = 'BoboVita Kaszka Mleczna Ryżowa 3 Owoce';

UPDATE products
SET ean = '5900852999383'
WHERE country = 'PL'
  AND brand = 'BoboVita'
  AND product_name = 'BoboVita Kaszka Zbożowa Jabłko Śliwka';

UPDATE products
SET ean = '5900852150005'
WHERE country = 'PL'
  AND brand = 'BoboVita'
  AND product_name = 'BoboVita Pomidorowa z kurczakiem i ryżem';

UPDATE products
SET ean = '5449000136350'
WHERE country = 'PL'
  AND brand = 'Cappy'
  AND product_name = 'Cappy 100% Orange';

UPDATE products
SET ean = '5900259068002'
WHERE country = 'PL'
  AND brand = 'Cheetos'
  AND product_name = 'Cheetos Cheese';

UPDATE products
SET ean = '5900259135360'
WHERE country = 'PL'
  AND brand = 'Cheetos'
  AND product_name = 'Cheetos Flamin Hot';

UPDATE products
SET ean = '5900259107350'
WHERE country = 'PL'
  AND brand = 'Cheetos'
  AND product_name = 'Cheetos Hamburger';

UPDATE products
SET ean = '5900259115614'
WHERE country = 'PL'
  AND brand = 'Cheetos'
  AND product_name = 'Cheetos Pizzerini';

UPDATE products
SET ean = '5449000130389'
WHERE country = 'PL'
  AND brand = 'Coca-Cola'
  AND product_name = 'Coca-Cola Original';

UPDATE products
SET ean = '5449000133328'
WHERE country = 'PL'
  AND brand = 'Coca-Cola'
  AND product_name = 'Coca-Cola Zero';

UPDATE products
SET ean = '5449000298928'
WHERE country = 'PL'
  AND brand = 'Costa Coffee'
  AND product_name = 'Costa Coffee Latte';

UPDATE products
SET ean = '20013011'
WHERE country = 'PL'
  AND brand = 'Crownfield (Lidl)'
  AND product_name = 'Crownfield Choco Balls';

UPDATE products
SET ean = '4056489978701'
WHERE country = 'PL'
  AND brand = 'Crownfield (Lidl)'
  AND product_name = 'Crownfield Choco Muszelki';

UPDATE products
SET ean = '20061449'
WHERE country = 'PL'
  AND brand = 'Crownfield (Lidl)'
  AND product_name = 'Crownfield Goldini';

UPDATE products
SET ean = '20202859'
WHERE country = 'PL'
  AND brand = 'Crownfield (Lidl)'
  AND product_name = 'Crownfield Musli Premium Multi-Frucht';

UPDATE products
SET ean = '5905187114845'
WHERE country = 'PL'
  AND brand = 'Crunchips'
  AND product_name = 'Crunchips Chakalaka';

UPDATE products
SET ean = '5905187114760'
WHERE country = 'PL'
  AND brand = 'Crunchips'
  AND product_name = 'Crunchips Pieczone Żeberka';

UPDATE products
SET ean = '5905187114685'
WHERE country = 'PL'
  AND brand = 'Crunchips'
  AND product_name = 'Crunchips X-Cut Papryka';

UPDATE products
SET ean = '5905187114692'
WHERE country = 'PL'
  AND brand = 'Crunchips'
  AND product_name = 'Crunchips X-Cut Solony';

UPDATE products
SET ean = '5905187114753'
WHERE country = 'PL'
  AND brand = 'Crunchips'
  AND product_name = 'Crunchips Zielona Cebulka';

UPDATE products
SET ean = '5901713020307'
WHERE country = 'PL'
  AND brand = 'Dawtona'
  AND product_name = 'Dawtona Sok Pomidorowy';

UPDATE products
SET ean = '5900259106667'
WHERE country = 'PL'
  AND brand = 'Doritos'
  AND product_name = 'Doritos BBQ';

UPDATE products
SET ean = '5900259094728'
WHERE country = 'PL'
  AND brand = 'Doritos'
  AND product_name = 'Doritos Hot Corn';

UPDATE products
SET ean = '5449000053541'
WHERE country = 'PL'
  AND brand = 'Fanta'
  AND product_name = 'Fanta Orange';

UPDATE products
SET ean = '5449000237620'
WHERE country = 'PL'
  AND brand = 'Fuze Tea'
  AND product_name = 'Fuze Tea Peach Hibiscus';

UPDATE products
SET ean = '8445291546851'
WHERE country = 'PL'
  AND brand = 'Gerber'
  AND product_name = 'Gerber Bukiet warzyw z łososiem w sosie pomidorowym';

UPDATE products
SET ean = '7613033512353'
WHERE country = 'PL'
  AND brand = 'Gerber'
  AND product_name = 'Gerber Krem jarzynowy ze schabem';

UPDATE products
SET ean = '7613035507142'
WHERE country = 'PL'
  AND brand = 'Gerber'
  AND product_name = 'Gerber Leczo z mozzarellą i kluseczkami';

UPDATE products
SET ean = '7613287173997'
WHERE country = 'PL'
  AND brand = 'Gerber'
  AND product_name = 'Gerber Pełnia Zbóż Owsianka 5 Zbóż';

UPDATE products
SET ean = '8445291546967'
WHERE country = 'PL'
  AND brand = 'Gerber'
  AND product_name = 'Gerber Warzywa z delikatnym indykiem w pomidorach';

UPDATE products
SET ean = '8000300435351'
WHERE country = 'PL'
  AND brand = 'Gerber'
  AND product_name = 'Gerber organic Krakersy z pomidorem po 12 miesiącu';

UPDATE products
SET ean = '7613033629303'
WHERE country = 'PL'
  AND brand = 'Gerber'
  AND product_name = 'Gerber owoce jabłka z truskawkami i jagodami';

UPDATE products
SET ean = '22009326'
WHERE country = 'PL'
  AND brand = 'GutBio'
  AND product_name = 'GutBio Puré de Frutas Manzana y Plátano';

UPDATE products
SET ean = '9062300109365'
WHERE country = 'PL'
  AND brand = 'HiPP'
  AND product_name = 'HiPP Dynia z indykiem';

UPDATE products
SET ean = '4062300279773'
WHERE country = 'PL'
  AND brand = 'HiPP'
  AND product_name = 'HiPP Kaszka mleczna z biszkoptami i jabłkami';

UPDATE products
SET ean = '9062300130833'
WHERE country = 'PL'
  AND brand = 'HiPP'
  AND product_name = 'HiPP Spaghetti z pomidorami i mozzarellą';

UPDATE products
SET ean = '9062300126638'
WHERE country = 'PL'
  AND brand = 'HiPP'
  AND product_name = 'HiPP Ziemniaki z buraczkami, jabłkiem i wołowiną';

UPDATE products
SET ean = '5900500031397'
WHERE country = 'PL'
  AND brand = 'Hortex'
  AND product_name = 'Hortex Sok Jabłkowy 100%';

UPDATE products
SET ean = '5900500031434'
WHERE country = 'PL'
  AND brand = 'Hortex'
  AND product_name = 'Hortex Sok Pomarańczowy 100%';

UPDATE products
SET ean = '5900334005052'
WHERE country = 'PL'
  AND brand = 'Kubuś'
  AND product_name = 'Kubuś Play Marchew-Jabłko';

UPDATE products
SET ean = '5906747171421'
WHERE country = 'PL'
  AND brand = 'Kupiec'
  AND product_name = 'Kupiec Coś na Ząb Owsianka';

UPDATE products
SET ean = '8722700406723'
WHERE country = 'PL'
  AND brand = 'Lipton'
  AND product_name = 'Lipton Ice Tea Lemon';

UPDATE products
SET ean = '5900049011621'
WHERE country = 'PL'
  AND brand = 'Lubella'
  AND product_name = 'Lubella Choco Piegotaki';

UPDATE products
SET ean = '5900049011645'
WHERE country = 'PL'
  AND brand = 'Lubella'
  AND product_name = 'Lubella Corn Flakes Pełne Ziarno';

UPDATE products
SET ean = '5900049812532'
WHERE country = 'PL'
  AND brand = 'Lubella'
  AND product_name = 'Lubella Płatki Żytnie';

UPDATE products
SET ean = '5906827003802'
WHERE country = 'PL'
  AND brand = 'Melvit'
  AND product_name = 'Melvit Płatki Owsiane Górskie';

UPDATE products
SET ean = '4060800102201'
WHERE country = 'PL'
  AND brand = 'Mirinda'
  AND product_name = 'Mirinda Orange';

UPDATE products
SET ean = '5900512300320'
WHERE country = 'PL'
  AND brand = 'Mlekovita'
  AND product_name = 'Mlekovita Mleko 3.2%';

UPDATE products
SET ean = '5060517883683'
WHERE country = 'PL'
  AND brand = 'Monster'
  AND product_name = 'Monster Energy Mango Loco';

UPDATE products
SET ean = '4060800207272'
WHERE country = 'PL'
  AND brand = 'Mountain Dew'
  AND product_name = 'Mountain Dew';

UPDATE products
SET ean = '5900020013491'
WHERE country = 'PL'
  AND brand = 'Nesquik'
  AND product_name = 'Nesquik Mix';

UPDATE products
SET ean = '5900020035929'
WHERE country = 'PL'
  AND brand = 'Nestlé'
  AND product_name = 'Nestlé Cheerios Owsiany';

UPDATE products
SET ean = '5900020000590'
WHERE country = 'PL'
  AND brand = 'Nestlé'
  AND product_name = 'Nestlé Chocapic';

UPDATE products
SET ean = '5900020002730'
WHERE country = 'PL'
  AND brand = 'Nestlé'
  AND product_name = 'Nestlé Cini Minis';

UPDATE products
SET ean = '5900020038593'
WHERE country = 'PL'
  AND brand = 'Nestlé'
  AND product_name = 'Nestlé Ciniminis Churros';

UPDATE products
SET ean = '5900020007728'
WHERE country = 'PL'
  AND brand = 'Nestlé'
  AND product_name = 'Nestlé Cookie Crisp';

UPDATE products
SET ean = '5900020019592'
WHERE country = 'PL'
  AND brand = 'Nestlé'
  AND product_name = 'Nestlé Corn Flakes';

UPDATE products
SET ean = '5900020021625'
WHERE country = 'PL'
  AND brand = 'Nestlé'
  AND product_name = 'Nestlé Lion Caramel & Chocolate';

UPDATE products
SET ean = '5900020020154'
WHERE country = 'PL'
  AND brand = 'Nestlé'
  AND product_name = 'Nestlé Nesquik Alphabet';

UPDATE products
SET ean = '7613287666819'
WHERE country = 'PL'
  AND brand = 'Nestlé'
  AND product_name = 'Nestlé Sinlac';

UPDATE products
SET ean = '5901958614408'
WHERE country = 'PL'
  AND brand = 'OWOLOVO'
  AND product_name = 'OWOLOVO Ananasowo';

UPDATE products
SET ean = '5901958612381'
WHERE country = 'PL'
  AND brand = 'OWOLOVO'
  AND product_name = 'OWOLOVO MORELOWO';

UPDATE products
SET ean = '5901958612640'
WHERE country = 'PL'
  AND brand = 'OWOLOVO'
  AND product_name = 'OWOLOVO Mus jabłkowo-wiśniowy';

UPDATE products
SET ean = '5901958612404'
WHERE country = 'PL'
  AND brand = 'OWOLOVO'
  AND product_name = 'OWOLOVO Siła & Moc Mus Jabłkowo-Buraczany';

UPDATE products
SET ean = '5901958614996'
WHERE country = 'PL'
  AND brand = 'OWOLOVO'
  AND product_name = 'OWOLOVO Smoothie tropikalne Jabłko Morela Pomarańcza';

UPDATE products
SET ean = '5901958612367'
WHERE country = 'PL'
  AND brand = 'OWOLOVO'
  AND product_name = 'OWOLOVO Truskawkowo Mus jabłkowo-truskawkowy';

UPDATE products
SET ean = '5900497312004'
WHERE country = 'PL'
  AND brand = 'Pepsi'
  AND product_name = 'Pepsi';

UPDATE products
SET ean = '5053990101573'
WHERE country = 'PL'
  AND brand = 'Pringles'
  AND product_name = 'Pringles Original';

UPDATE products
SET ean = '5053990161669'
WHERE country = 'PL'
  AND brand = 'Pringles'
  AND product_name = 'Pringles Paprika';

UPDATE products
SET ean = '5053990101597'
WHERE country = 'PL'
  AND brand = 'Pringles'
  AND product_name = 'Pringles Sour Cream & Onion';

UPDATE products
SET ean = '9002490100070'
WHERE country = 'PL'
  AND brand = 'Red Bull'
  AND product_name = 'Red Bull Energy Drink';

UPDATE products
SET ean = '5900617037213'
WHERE country = 'PL'
  AND brand = 'Sante'
  AND product_name = 'Sante Fit Granola Truskawka & Wiśnia';

UPDATE products
SET ean = '5900617037152'
WHERE country = 'PL'
  AND brand = 'Sante'
  AND product_name = 'Sante Gold Granola';

UPDATE products
SET ean = '5900617037176'
WHERE country = 'PL'
  AND brand = 'Sante'
  AND product_name = 'Sante Granola Czekolada & Pomarańcza';

UPDATE products
SET ean = '5900617002969'
WHERE country = 'PL'
  AND brand = 'Sante'
  AND product_name = 'Sante Granola Malina & Truskawka';

UPDATE products
SET ean = '5900617002976'
WHERE country = 'PL'
  AND brand = 'Sante'
  AND product_name = 'Sante Granola Nut';

UPDATE products
SET ean = '4056489486459'
WHERE country = 'PL'
  AND brand = 'Snack Day (Lidl)'
  AND product_name = 'Snack Day Chipsy Solone';

UPDATE products
SET ean = '4056489405115'
WHERE country = 'PL'
  AND brand = 'Snack Day (Lidl)'
  AND product_name = 'Snack Day Mega Karbowane Słodkie Chilli';

UPDATE products
SET ean = '5449000004840'
WHERE country = 'PL'
  AND brand = 'Sprite'
  AND product_name = 'Sprite';

UPDATE products
SET ean = '5900259087898'
WHERE country = 'PL'
  AND brand = 'Star'
  AND product_name = 'Star Maczugi';

UPDATE products
SET ean = '5908308911309'
WHERE country = 'PL'
  AND brand = 'Szamamm'
  AND product_name = 'Gnocchi z kurczakiem';

UPDATE products
SET ean = '10471346'
WHERE country = 'PL'
  AND brand = 'Szamamm'
  AND product_name = 'Kotlet Drobiowy';

UPDATE products
SET ean = '06638993'
WHERE country = 'PL'
  AND brand = 'Szamamm'
  AND product_name = 'Kotlet de Volaille';

UPDATE products
SET ean = '5901398082379'
WHERE country = 'PL'
  AND brand = 'Szamamm'
  AND product_name = 'Naleśniki z jabłkami i cynamonem';

UPDATE products
SET ean = '5900757067941'
WHERE country = 'PL'
  AND brand = 'Szamamm'
  AND product_name = 'Panierowane skrzydełka z kurczaka';

UPDATE products
SET ean = '5908308902093'
WHERE country = 'PL'
  AND brand = 'Szamamm'
  AND product_name = 'Penne z kurczakiem';

UPDATE products
SET ean = '00719063'
WHERE country = 'PL'
  AND brand = 'Szamamm'
  AND product_name = 'Pierogi ruskie ze smażoną cebulką';

UPDATE products
SET ean = '04998358'
WHERE country = 'PL'
  AND brand = 'Szamamm'
  AND product_name = 'Placki ziemniaczane';

UPDATE products
SET ean = '5900334008206'
WHERE country = 'PL'
  AND brand = 'Tiger'
  AND product_name = 'Tiger Energy Drink';

UPDATE products
SET ean = '5900334009142'
WHERE country = 'PL'
  AND brand = 'Tiger'
  AND product_name = 'Tiger Energy Drink Classic';

UPDATE products
SET ean = '8586015136399'
WHERE country = 'PL'
  AND brand = 'Tomcio Paluch'
  AND product_name = 'BBQ Strips';

UPDATE products
SET ean = '5903111184339'
WHERE country = 'PL'
  AND brand = 'Tomcio Paluch'
  AND product_name = 'Bajgiel z salami';

UPDATE products
SET ean = '8586020105540'
WHERE country = 'PL'
  AND brand = 'Tomcio Paluch'
  AND product_name = 'High 24g protein';

UPDATE products
SET ean = '8586020100064'
WHERE country = 'PL'
  AND brand = 'Tomcio Paluch'
  AND product_name = 'Kanapka Cezar';

UPDATE products
SET ean = '8586015136382'
WHERE country = 'PL'
  AND brand = 'Tomcio Paluch'
  AND product_name = 'Kebab z kurczaka';

UPDATE products
SET ean = '8586020103768'
WHERE country = 'PL'
  AND brand = 'Tomcio Paluch'
  AND product_name = 'Pasta jajeczna, por, jajko gotowane';

UPDATE products
SET ean = '8586020104505'
WHERE country = 'PL'
  AND brand = 'Tomcio Paluch'
  AND product_name = 'Pieczony bekon, sałata, jajko';

UPDATE products
SET ean = '8586020103553'
WHERE country = 'PL'
  AND brand = 'Tomcio Paluch'
  AND product_name = 'Szynka & Jajko';

UPDATE products
SET ean = '5900073400576'
WHERE country = 'PL'
  AND brand = 'Top Chips (Biedronka)'
  AND product_name = 'Top Chips Faliste';

UPDATE products
SET ean = '5900073021269'
WHERE country = 'PL'
  AND brand = 'Top Chips (Biedronka)'
  AND product_name = 'Top Chips Fromage';

UPDATE products
SET ean = '5900334001047'
WHERE country = 'PL'
  AND brand = 'Tymbark'
  AND product_name = 'Tymbark Cactus';

UPDATE products
SET ean = '5900334013378'
WHERE country = 'PL'
  AND brand = 'Tymbark'
  AND product_name = 'Tymbark Multiwitamina';

UPDATE products
SET ean = '5900334003935'
WHERE country = 'PL'
  AND brand = 'Tymbark'
  AND product_name = 'Tymbark Mus gruszka jabłko';

UPDATE products
SET ean = '5900334005939'
WHERE country = 'PL'
  AND brand = 'Tymbark'
  AND product_name = 'Tymbark Sok 100% Jabłkowy';

UPDATE products
SET ean = '5900334012685'
WHERE country = 'PL'
  AND brand = 'Tymbark'
  AND product_name = 'Tymbark Sok 100% Pomarańczowy';

UPDATE products
SET ean = '5907437366059'
WHERE country = 'PL'
  AND brand = 'Vitanella (Biedronka)'
  AND product_name = 'Vitanella Choki';

UPDATE products
SET ean = '5907437361474'
WHERE country = 'PL'
  AND brand = 'Vitanella (Biedronka)'
  AND product_name = 'Vitanella Corn Flakes';

UPDATE products
SET ean = '5900749610520'
WHERE country = 'PL'
  AND brand = 'Vitanella (Biedronka)'
  AND product_name = 'Vitanella Crunchy Owocowe';

UPDATE products
SET ean = '5907437365489'
WHERE country = 'PL'
  AND brand = 'Vitanella (Biedronka)'
  AND product_name = 'Vitanella Miami Hopki';

UPDATE products
SET ean = '5907437367919'
WHERE country = 'PL'
  AND brand = 'Vitanella (Biedronka)'
  AND product_name = 'Vitanella Orito Kakaowe';

UPDATE products
SET ean = '5905187109025'
WHERE country = 'PL'
  AND brand = 'Wiejskie Ziemniaczki'
  AND product_name = 'Wiejskie Ziemniaczki Cebulka';

UPDATE products
SET ean = '5905187108981'
WHERE country = 'PL'
  AND brand = 'Wiejskie Ziemniaczki'
  AND product_name = 'Wiejskie Ziemniaczki Masło z Solą';

UPDATE products
SET ean = '8436550903003'
WHERE country = 'PL'
  AND brand = 'dada baby food'
  AND product_name = 'dada baby food bio mus kokos';

UPDATE products
SET ean = '5900820000073'
WHERE country = 'PL'
  AND brand = 'Łaciate'
  AND product_name = 'Łaciate Mleko 2%';

UPDATE products
SET ean = '5908308911019'
WHERE country = 'PL'
  AND brand = 'Żabka'
  AND product_name = 'Bao Burger';

UPDATE products
SET ean = '5908308910791'
WHERE country = 'PL'
  AND brand = 'Żabka'
  AND product_name = 'Burger Kibica';

UPDATE products
SET ean = '5903738866274'
WHERE country = 'PL'
  AND brand = 'Żabka'
  AND product_name = 'Falafel Rollo';

UPDATE products
SET ean = '5903111184766'
WHERE country = 'PL'
  AND brand = 'Żabka'
  AND product_name = 'Kajzerka Kebab';

UPDATE products
SET ean = '5903548012045'
WHERE country = 'PL'
  AND brand = 'Żabka'
  AND product_name = 'Kulki owsiane z czekoladą';

UPDATE products
SET ean = '2050000554995'
WHERE country = 'PL'
  AND brand = 'Żabka'
  AND product_name = 'Kurczaker';

UPDATE products
SET ean = '2050000645372'
WHERE country = 'PL'
  AND brand = 'Żabka'
  AND product_name = 'Meksykaner';

UPDATE products
SET ean = '2040100470387'
WHERE country = 'PL'
  AND brand = 'Żabka'
  AND product_name = 'Panini z kurczakiem';

UPDATE products
SET ean = '5908308908729'
WHERE country = 'PL'
  AND brand = 'Żabka'
  AND product_name = 'Panini z serem cheddar';

UPDATE products
SET ean = '2050000557415'
WHERE country = 'PL'
  AND brand = 'Żabka'
  AND product_name = 'Wegger';

UPDATE products
SET ean = '5908308911637'
WHERE country = 'PL'
  AND brand = 'Żabka'
  AND product_name = 'Wieprzowiner';

UPDATE products
SET ean = '5908308910043'
WHERE country = 'PL'
  AND brand = 'Żabka'
  AND product_name = 'Wołowiner Ser Kozi';

UPDATE products
SET ean = '5900134001353'
WHERE country = 'PL'
  AND brand = 'Żywiec Zdrój'
  AND product_name = 'Żywiec Zdrój Smako-łyk Truskawka';

-- =============================================================================
-- Verification query
-- =============================================================================

SELECT
  COUNT(*) AS total_products,
  COUNT(ean) AS products_with_ean,
  ROUND(100.0 * COUNT(ean) / COUNT(*), 1) AS ean_coverage_pct
FROM products
WHERE is_deprecated IS NOT TRUE;
