-- Migration: Add verified EANs to Plant-Based & Alternatives category (11 products)
-- Date: 2026-02-08
-- Found via Open Food Facts API research
-- All EANs validated using GS1 Modulo-10 checksum
-- Success rate: 11/27 (40.7%)
-- Note: Plant-Based category has duplicate products (2 of each) - only updating first product_id

UPDATE products SET ean = '0850004207390' WHERE brand = 'Beyond Meat' AND product_name = 'Beyond Meat Beyond Burger' AND category = 'Plant-Based & Alternatives' AND product_id = (SELECT MIN(product_id) FROM products WHERE brand = 'Beyond Meat' AND product_name = 'Beyond Meat Beyond Burger' AND category = 'Plant-Based & Alternatives');
UPDATE products SET ean = '0852629004774' WHERE brand = 'Beyond Meat' AND product_name = 'Beyond Meat Beyond Sausage' AND category = 'Plant-Based & Alternatives' AND product_id = (SELECT MIN(product_id) FROM products WHERE brand = 'Beyond Meat' AND product_name = 'Beyond Meat Beyond Sausage' AND category = 'Plant-Based & Alternatives');
UPDATE products SET ean = '7613037397956' WHERE brand = 'Garden Gourmet' AND product_name = 'Garden Gourmet Sensational Burger' AND category = 'Plant-Based & Alternatives' AND product_id = (SELECT MIN(product_id) FROM products WHERE brand = 'Garden Gourmet' AND product_name = 'Garden Gourmet Sensational Burger' AND category = 'Plant-Based & Alternatives');
UPDATE products SET ean = '7613287419613' WHERE brand = 'Garden Gourmet' AND product_name = 'Garden Gourmet Vegan Mince' AND category = 'Plant-Based & Alternatives' AND product_id = (SELECT MIN(product_id) FROM products WHERE brand = 'Garden Gourmet' AND product_name = 'Garden Gourmet Vegan Mince' AND category = 'Plant-Based & Alternatives');
UPDATE products SET ean = '7613036021265' WHERE brand = 'Garden Gourmet' AND product_name = 'Garden Gourmet Vegan Nuggets' AND category = 'Plant-Based & Alternatives' AND product_id = (SELECT MIN(product_id) FROM products WHERE brand = 'Garden Gourmet' AND product_name = 'Garden Gourmet Vegan Nuggets' AND category = 'Plant-Based & Alternatives');
UPDATE products SET ean = '7613287424587' WHERE brand = 'Garden Gourmet' AND product_name = 'Garden Gourmet Vegan Schnitzel' AND category = 'Plant-Based & Alternatives' AND product_id = (SELECT MIN(product_id) FROM products WHERE brand = 'Garden Gourmet' AND product_name = 'Garden Gourmet Vegan Schnitzel' AND category = 'Plant-Based & Alternatives');
UPDATE products SET ean = '4012359180001' WHERE brand = 'Taifun' AND product_name = 'Taifun Tofu Natural' AND category = 'Plant-Based & Alternatives' AND product_id = (SELECT MIN(product_id) FROM products WHERE brand = 'Taifun' AND product_name = 'Taifun Tofu Natural' AND category = 'Plant-Based & Alternatives');
UPDATE products SET ean = '4012359114303' WHERE brand = 'Taifun' AND product_name = 'Taifun Tofu Rosso' AND category = 'Plant-Based & Alternatives' AND product_id = (SELECT MIN(product_id) FROM products WHERE brand = 'Taifun' AND product_name = 'Taifun Tofu Rosso' AND category = 'Plant-Based & Alternatives');
UPDATE products SET ean = '4012359010599' WHERE brand = 'Taifun' AND product_name = 'Taifun Tofu Smoked' AND category = 'Plant-Based & Alternatives' AND product_id = (SELECT MIN(product_id) FROM products WHERE brand = 'Taifun' AND product_name = 'Taifun Tofu Smoked' AND category = 'Plant-Based & Alternatives');
UPDATE products SET ean = '5202390023576' WHERE brand = 'Violife' AND product_name = 'Violife Cheddar Slices' AND category = 'Plant-Based & Alternatives' AND product_id = (SELECT MIN(product_id) FROM products WHERE brand = 'Violife' AND product_name = 'Violife Cheddar Slices' AND category = 'Plant-Based & Alternatives');
UPDATE products SET ean = '5202390015427' WHERE brand = 'Violife' AND product_name = 'Violife Original Block' AND category = 'Plant-Based & Alternatives' AND product_id = (SELECT MIN(product_id) FROM products WHERE brand = 'Violife' AND product_name = 'Violife Original Block' AND category = 'Plant-Based & Alternatives');
