-- PIPELINE (Bread): scoring
-- Generated: 2026-02-09

-- 2. Nutri-Score
update products p set
  nutri_score_label = d.ns
from (
  values
    ('Gursz', 'Chleb Pszenno-Żytni', 'C'),
    ('Lajkonik', 'Paluszki słone', 'D'),
    ('Dan Cake', 'Bułeczki mleczne z czekoladą', 'D'),
    ('Pano', 'Chleb mieszany pszenno-żytni z dodatkiem naturalnego zakwasu żytniego oraz ziaren, krojony. Złoty łan', 'B'),
    ('Pano', 'Hot dog pszenno-żytni', 'C'),
    ('Mestemacher', 'Chleb wielozbożowy żytni pełnoziarnisty', 'B'),
    ('Auchan', 'Bułki do Hamburgerów', 'D'),
    ('Auchan', 'Tost pełnoziarnisty', 'C'),
    ('Vital', 'Bułki śniadaniowe', 'C'),
    ('Pano', 'Bułka tarta', 'A'),
    ('Piekarnia Gwóźdź', 'Chleb z mąką krojony - pieczywo mieszane', 'C'),
    ('Pano', 'Bułka do hot doga', 'D'),
    ('Auchan', 'Tortilla Pszenno-Żytnia', 'D'),
    ('Pano', 'Tost pełnoziarnisty', 'B'),
    ('Pano', 'Tost maślany', 'C'),
    ('Melvit', 'Pieczywo Chrupkie Zytnie CRISPY z pomidorami i bazylią', 'D'),
    ('Pano', 'Chleb żytni', 'A'),
    ('Dan Cake', 'Mleczne bułeczki', 'D'),
    ('Sonko', 'Lekkie żytnie', 'B'),
    ('Lantmannen Unibake', 'Bułki pszenne do hot dogów', 'C'),
    ('Aksam', 'Beskidzkie paluszki z solą', 'E'),
    ('Wypieczone ze smakiem', 'Chleb żytni z ziarnami', 'C'),
    ('Pano', 'Bułeczki śniadaniowe', 'D'),
    ('Spółdzielnia piekarsko ciastkarska w Warszawie', 'Chleb wieloziarnisty złoty łan', 'B'),
    ('Pano', 'Chleb wieloziarnisty Złoty Łan', 'E'),
    ('Z Piekarni Regionalnej', 'Chleb zytni ze słonecznikiem', 'C'),
    ('Pano', 'Bułki do hamburgerów z sezamem', 'C'),
    ('Sonko', 'Lekkie ze słonecznikiem', 'UNKNOWN'),
    ('Mastemacher', 'Chleb żytni', 'C'),
    ('Sendal', 'Chleb firmowy, pieczywo mieszane pszenno-żytnie', 'C'),
    ('Carrefour', 'Chleb tostowy maślany', 'C'),
    ('Oskroba', 'Chleb żytni razowy', 'C'),
    ('Vital', 'Bułki z ziarnami', 'C'),
    ('Dan Cake', 'Bułki śniadaniowe', 'C'),
    ('Sendal', 'Chleb na maślance', 'C'),
    ('Lajkonik', 'Bajgle z ziołami prowansalskimi', 'D'),
    ('Dan Cake', 'Tost pełnoziarnisty', 'C'),
    ('Piekarnia Wilkowo', 'Chleb pszenno-żytni', 'C'),
    ('Dan Cake', 'Bułeczki pszenne częściowo pieczone - do samodzielnego wypieku', 'C'),
    ('Sendal', 'Chleb żytni bez drożdzy', 'B'),
    ('Piekarnia Oskrobia', 'Chleb-pszenno-żytni z mąką pełnoziarnistą graham oraz dodatkiem zakwasu żytniego, krojony', 'C'),
    ('Mika', 'Chleb żytni razowy', 'C'),
    ('Putka', 'Tost z mąką pełnoziarnistą (pszenno-żytni)', 'B'),
    ('Pano', 'Tortilla', 'C'),
    ('Pano', 'Chleb żytni z dodatkiem amarantusa i komosy ryżowej', 'A'),
    ('Pano', 'Pieczywo kukurydziane chrupkie', 'C'),
    ('Bite IT', 'LAWASZ pszenny chleb', 'C'),
    ('Gwóźdź', 'Chleb wieloziarnisty', 'B'),
    ('Oskroba', 'Tost maślany', 'C'),
    ('Z Dobrej Piekarni', 'Chleb baltonowski', 'C'),
    ('Carrefour', 'Tortilla pszenna', 'C'),
    ('Z Dobrej Piekarni', 'Chleb wieloziarnisty', 'C'),
    ('Shulstad', 'Classic Pszenny Hot Dog', 'B'),
    ('Oskroba', 'Chleb żytni pełnoziarnisty pasteryzowany', 'C'),
    ('Dakri', 'Pinsa', 'C'),
    ('Żabka', 'Kajzerka kebab', 'D'),
    ('Asprod', 'Chleb jakubowy żytni razowy', 'A'),
    ('Biedronka piekarnia gwóźdź', 'Chleb żytni', 'D'),
    ('Piekarnia "Pod Rogalem"', 'Chleb Baltonowski krojony', 'C'),
    ('Piekarnia Jesse', 'Chleb wieloziarnisty ciemny', 'C')
) as d(brand, product_name, ns)
where p.country = 'PL' and p.brand = d.brand and p.product_name = d.product_name;

-- 3. NOVA classification
update products p set
  nova_classification = d.nova
from (
  values
    ('Gursz', 'Chleb Pszenno-Żytni', '4'),
    ('Lajkonik', 'Paluszki słone', '3'),
    ('Dan Cake', 'Bułeczki mleczne z czekoladą', '4'),
    ('Pano', 'Chleb mieszany pszenno-żytni z dodatkiem naturalnego zakwasu żytniego oraz ziaren, krojony. Złoty łan', '4'),
    ('Pano', 'Hot dog pszenno-żytni', '4'),
    ('Mestemacher', 'Chleb wielozbożowy żytni pełnoziarnisty', '4'),
    ('Auchan', 'Bułki do Hamburgerów', '3'),
    ('Auchan', 'Tost pełnoziarnisty', '4'),
    ('Vital', 'Bułki śniadaniowe', '4'),
    ('Pano', 'Bułka tarta', '3'),
    ('Piekarnia Gwóźdź', 'Chleb z mąką krojony - pieczywo mieszane', '4'),
    ('Pano', 'Bułka do hot doga', '4'),
    ('Auchan', 'Tortilla Pszenno-Żytnia', '4'),
    ('Pano', 'Tost pełnoziarnisty', '4'),
    ('Pano', 'Tost maślany', '3'),
    ('Melvit', 'Pieczywo Chrupkie Zytnie CRISPY z pomidorami i bazylią', '3'),
    ('Pano', 'Chleb żytni', '3'),
    ('Dan Cake', 'Mleczne bułeczki', '4'),
    ('Sonko', 'Lekkie żytnie', '4'),
    ('Lantmannen Unibake', 'Bułki pszenne do hot dogów', '3'),
    ('Aksam', 'Beskidzkie paluszki z solą', '4'),
    ('Wypieczone ze smakiem', 'Chleb żytni z ziarnami', '4'),
    ('Pano', 'Bułeczki śniadaniowe', '4'),
    ('Spółdzielnia piekarsko ciastkarska w Warszawie', 'Chleb wieloziarnisty złoty łan', '4'),
    ('Pano', 'Chleb wieloziarnisty Złoty Łan', '4'),
    ('Z Piekarni Regionalnej', 'Chleb zytni ze słonecznikiem', '1'),
    ('Pano', 'Bułki do hamburgerów z sezamem', '4'),
    ('Sonko', 'Lekkie ze słonecznikiem', '4'),
    ('Mastemacher', 'Chleb żytni', '4'),
    ('Sendal', 'Chleb firmowy, pieczywo mieszane pszenno-żytnie', '3'),
    ('Carrefour', 'Chleb tostowy maślany', '4'),
    ('Oskroba', 'Chleb żytni razowy', '4'),
    ('Vital', 'Bułki z ziarnami', '4'),
    ('Dan Cake', 'Bułki śniadaniowe', '4'),
    ('Sendal', 'Chleb na maślance', '4'),
    ('Lajkonik', 'Bajgle z ziołami prowansalskimi', '4'),
    ('Dan Cake', 'Tost pełnoziarnisty', '3'),
    ('Piekarnia Wilkowo', 'Chleb pszenno-żytni', '4'),
    ('Dan Cake', 'Bułeczki pszenne częściowo pieczone - do samodzielnego wypieku', '4'),
    ('Sendal', 'Chleb żytni bez drożdzy', '3'),
    ('Piekarnia Oskrobia', 'Chleb-pszenno-żytni z mąką pełnoziarnistą graham oraz dodatkiem zakwasu żytniego, krojony', '4'),
    ('Mika', 'Chleb żytni razowy', '3'),
    ('Putka', 'Tost z mąką pełnoziarnistą (pszenno-żytni)', '4'),
    ('Pano', 'Tortilla', '4'),
    ('Pano', 'Chleb żytni z dodatkiem amarantusa i komosy ryżowej', '4'),
    ('Pano', 'Pieczywo kukurydziane chrupkie', '3'),
    ('Bite IT', 'LAWASZ pszenny chleb', '3'),
    ('Gwóźdź', 'Chleb wieloziarnisty', '4'),
    ('Oskroba', 'Tost maślany', '4'),
    ('Z Dobrej Piekarni', 'Chleb baltonowski', '3'),
    ('Carrefour', 'Tortilla pszenna', '4'),
    ('Z Dobrej Piekarni', 'Chleb wieloziarnisty', '3'),
    ('Shulstad', 'Classic Pszenny Hot Dog', '4'),
    ('Oskroba', 'Chleb żytni pełnoziarnisty pasteryzowany', '4'),
    ('Dakri', 'Pinsa', '4'),
    ('Żabka', 'Kajzerka kebab', '4'),
    ('Asprod', 'Chleb jakubowy żytni razowy', '4'),
    ('Biedronka piekarnia gwóźdź', 'Chleb żytni', '4'),
    ('Piekarnia "Pod Rogalem"', 'Chleb Baltonowski krojony', '3'),
    ('Piekarnia Jesse', 'Chleb wieloziarnisty ciemny', '4')
) as d(brand, product_name, nova)
where p.country = 'PL' and p.brand = d.brand and p.product_name = d.product_name;

-- 0/1/4/5. Score category (concern defaults, unhealthiness, flags, confidence)
CALL score_category('Bread');
