"""
Extract EAN codes from pipeline SQL comments and generate UPDATE statements.

Parses all PIPELINE__*__01_insert_products.sql files and extracts:
- EAN codes from comments (format: -- EAN 1234567890123)
- Brand and product name from the INSERT statement on the next line
- Generates UPDATE statements to populate products.ean column

Usage:
    python extract_eans.py > db/migrations/20260208_populate_eans.sql
"""

import re
from pathlib import Path
from typing import List, Tuple

def extract_eans_from_file(filepath: Path) -> List[Tuple[str, str, str]]:
    """
    Extract (EAN, brand, product_name) tuples from a pipeline SQL file.
    
    Returns:
        List of (ean, brand, product_name) tuples
    """
    results = []
    
    with open(filepath, 'r', encoding='utf-8') as f:
        lines = f.readlines()
    
    for i, line in enumerate(lines):
        # Look for EAN comment lines
        ean_match = re.search(r'-- EAN (\d{8,13})', line)
        if ean_match and i + 1 < len(lines):
            ean = ean_match.group(1)
            next_line = lines[i + 1]
            
            # Parse the INSERT VALUES line
            # Format: ('PL','Brand','Type','Category','Product Name',...
            insert_match = re.search(
                r"\('PL','([^']+)','[^']+','[^']+','([^']+)'",
                next_line
            )
            
            if insert_match:
                brand = insert_match.group(1)
                product_name = insert_match.group(2)
                results.append((ean, brand, product_name))
    
    return results

def main():
    # Find all 01_insert_products.sql files
    db_path = Path(__file__).parent / 'db' / 'pipelines'
    insert_files = sorted(db_path.glob('*/PIPELINE__*__01_insert_products.sql'))
    
    all_eans = []
    
    for filepath in insert_files:
        category = filepath.parent.name
        eans = extract_eans_from_file(filepath)
        all_eans.extend(eans)
        print(f"-- Found {len(eans)} EANs in {category}", file=__import__('sys').stderr)
    
    # Generate migration SQL
    print("-- MIGRATION: Populate products.ean column from pipeline comments")
    print("-- Generated by extract_eans.py")
    print("-- DO NOT EDIT MANUALLY - regenerate by running the script")
    print()
    print("-- ═════════════════════════════════════════════════════════════════════════")
    print("-- Populate EAN codes extracted from pipeline SQL comments")
    print("-- ═════════════════════════════════════════════════════════════════════════")
    print()
    
    for ean, brand, product_name in sorted(all_eans, key=lambda x: (x[1], x[2])):
        # Escape single quotes in product names
        safe_product_name = product_name.replace("'", "''")
        safe_brand = brand.replace("'", "''")
        
        print(f"UPDATE products")
        print(f"SET ean = '{ean}'")
        print(f"WHERE country = 'PL'")
        print(f"  AND brand = '{safe_brand}'")
        print(f"  AND product_name = '{safe_product_name}';")
        print()
    
    print("-- ═════════════════════════════════════════════════════════════════════════")
    print("-- Verification query")
    print("-- ═════════════════════════════════════════════════════════════════════════")
    print()
    print("SELECT")
    print("  COUNT(*) AS total_products,")
    print("  COUNT(ean) AS products_with_ean,")
    print("  ROUND(100.0 * COUNT(ean) / COUNT(*), 1) AS ean_coverage_pct")
    print("FROM products")
    print("WHERE is_deprecated IS NOT TRUE;")

if __name__ == '__main__':
    main()
