name: Bug Report
description: Report a bug or unexpected behavior in the Poland Food DB.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below so we can reproduce and fix it quickly.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug.
      placeholder: "When I do X, Y happens instead of Z."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened. Include error messages, screenshots, or logs if available.
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where did you observe this bug?
      options:
        - Local (supabase db reset)
        - Staging
        - Production
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Which area of the project is affected?
      options:
        - Frontend (Next.js / React)
        - Backend (SQL functions / RPC)
        - Data (products / nutrition / ingredients)
        - Scoring (unhealthiness formula)
        - Pipeline (Python / OFF API)
        - CI / Infrastructure
        - Documentation
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - P0 — Critical (data loss, security, site down)
        - P1 — High (major feature broken, no workaround)
        - P2 — Medium (feature broken, workaround exists)
        - P3 — Low (cosmetic, minor inconvenience)
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Logs
      description: If applicable, add screenshots or relevant log output.
      render: shell
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context about the problem (browser, OS, related issues, etc.).
    validations:
      required: false
