name: Feature Request
description: Propose a new feature or enhancement for the Poland Food DB.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement! Please follow the project's [Feature Implementation Standard](https://github.com/ericsocrat/poland-food-db/blob/main/copilot-instructions.md#15-feature-implementation-standard) for significant features.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: |
        What user/developer/system problem does this solve? Be specific — include a concrete scenario.
      placeholder: "As a user browsing the Dairy category, I want to ... so that ..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe what you'd like to happen. Include technical approach if you have one.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: List any alternative solutions or features you've considered and why they were rejected.
    validations:
      required: false

  - type: dropdown
    id: workstream
    attributes:
      label: Workstream
      description: Which area of the project does this affect?
      options:
        - Frontend
        - Backend (SQL / API)
        - Data / Pipeline
        - Scoring
        - CI / Infrastructure
        - Security
        - Governance / Documentation
    validations:
      required: true

  - type: dropdown
    id: effort
    attributes:
      label: Estimated Effort
      description: How much work do you think this requires?
      options:
        - Small (< 1 day)
        - Medium (1–3 days)
        - Large (3–7 days)
        - Extra Large (> 1 week)
    validations:
      required: false

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: |
        Specific, verifiable conditions that must be true when this feature is complete.
      placeholder: |
        - [ ] New API function `api_xyz()` returns expected JSONB shape
        - [ ] pgTAP test covers happy path and error branches
        - [ ] QA suite passes with no new failures
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, mockups, or references. Link related issues.
    validations:
      required: false
