-- PIPELINE (Sauces): scoring
-- Generated: 2026-02-09

-- 2. Nutri-Score
update products p set
  nutri_score_label = d.ns
from (
  values
    ('Pudliszki', 'Po Bolońsku sos do spaghetti', 'B'),
    ('Culineo', 'Sos meksykański', 'C'),
    ('Dawtona', 'Sos do spaghetti pomidorowo-śmietankowy', 'C'),
    ('Dawtona', 'Sos Neapolitański z papryką', 'C'),
    ('Dawtona', 'Sos Boloński z ziołami', 'C'),
    ('Dawtona', 'Sos meksykański', 'C'),
    ('Dawtona', 'Sos słodko-kwaśny z ananasem', 'C'),
    ('Polskie Przetwory', 'Sos Boloński z bazylią', 'C'),
    ('Międzychód', 'Sos Boloński z mięsem', 'C'),
    ('Roleski', 'Sos tysiąca wysp', 'D'),
    ('Heinz', 'Sos tysiąca wysp', 'D'),
    ('Heinz', 'Sos Barbecue. Sos do grilla z cebulą i papryką', 'E'),
    ('Fanex', 'Sos meksykański', 'C'),
    ('Łowicz', 'Sos Boloński', 'A'),
    ('Culineo', 'Sos boloński', 'C'),
    ('Dawtona', 'Sos do pizzy z ziołami', 'C'),
    ('Roleski', 'Sos pomidor + miód + limonka + nasiona chia', 'D'),
    ('Pudliszki', 'Duszone pomidory o smaku smażonej cebuli i czosnku, z olejem', 'A'),
    ('Fanex', 'Sos tysiąc wysp', 'UNKNOWN'),
    ('Vital FRESH', 'Sałatka w stylu greckim', 'C'),
    ('Vifon', 'Sos chili tajski słodko-pikantny', 'D'),
    ('Sottile Gusto', 'Passata z czosnkiem', 'B'),
    ('Sottile Gusto', 'Passata', 'A'),
    ('Dawtona', 'Sos Pomidorowy do Makaronu', 'C'),
    ('Międzychód', 'Sos pomidorowy', 'C'),
    ('Dawtona', 'Sos Curry', 'E'),
    ('Carrefour', 'Przecier pomidorowy', 'UNKNOWN'),
    ('Culineo', 'SOS Spaghetti', 'C'),
    ('Develey', 'Sos 1000 wysp', 'C'),
    ('Madero', 'Sos jogurtowy z ziołami', 'UNKNOWN'),
    ('Go Vege', 'Sos z jalapeño', 'D'),
    ('Biedronka', 'Sos z chili', 'D'),
    ('Vifon', 'Sos chili pikantny', 'E'),
    ('Develey', 'Sos jalapeño', 'C'),
    ('Dawtona', 'Sos BBQ', 'D'),
    ('Madero', 'Sos BBQ z chipotle', 'C'),
    ('Łowicz', 'Sos Spaghetti', 'C'),
    ('Pudliszki', 'Sos Do Spaghetti Oryginalny', 'B'),
    ('Dawtona', 'Passata rustica', 'A'),
    ('Pudliszki', 'Przecier pomidorowy', 'A'),
    ('Łowicz', 'Leczo', 'UNKNOWN'),
    ('Roleski', 'Avocaboo!', 'D'),
    ('Sottile Gusto', 'Przecier pomidorowy', 'A'),
    ('Jamar', 'Passata - przecier pomidorowy klasyczny', 'B'),
    ('Roleski', 'Sos do kurczaka z czosnkiem', 'D'),
    ('Rolnik', 'Passata', 'A'),
    ('GustoBello', 'Arrabbiata Bruschetta', 'C'),
    ('Helcom', 'Dip in mexicana style', 'C'),
    ('Roleski', 'Sos pomidor + czarnuszka ostry', 'D'),
    ('Roleski', 'Sos pomidor + jagody goji', 'D'),
    ('MW Food', 'Sauce tomate', 'A'),
    ('Pudliszki', 'Bolonski', 'C'),
    ('Biedronka', 'Pesto Zielone. Sos na bazie bazyli', 'D'),
    ('GustoBello', 'White wine vinegar cream with pesto alla genovese', 'D'),
    ('Kucharek', 'Kucharek', 'E'),
    ('Roleski', 'Sos vinaigrette', 'D'),
    ('Knorr', 'Sos sałatkowy paprykowo-ziołowy', 'E'),
    ('Madero', 'Sos chilli pikantny', 'D'),
    ('Asia Flavours', 'Sos Sriracha mayo', 'E'),
    ('House of asia', 'Sos Sriracha', 'E'),
    ('Asia Flavours', 'Sos Sambal Oelek', 'E'),
    ('House of Asia', 'Sos z Czarnym Pieprzem', 'E'),
    ('Madero', 'Sos BBQ z miodem gryczanym', 'E'),
    ('Roleski', 'BBQ sos whisky', 'E'),
    ('Roleski', 'Texas sos BBQ', 'E'),
    ('Kotlin', 'Sos BBQ', 'D'),
    ('Jamar', 'Passata klasyczna', 'B'),
    ('Waldi Ben', 'Koncentrat pomidorowy 30%', 'C'),
    ('Winiary', 'Spaghetti sos z pomidorów', 'B'),
    ('Pingo Doce', 'Sos pomidorowy z bazylią', 'A'),
    ('Podravka', 'Przecier pomidorowy z bazylią', 'A'),
    ('Helcom', 'Sauce a la mexicaine', 'C'),
    ('Dawtona', 'Sos pomidorowy ostry z papryczkami jalapeño', 'C'),
    ('Schedro', 'Sos Chersoński', 'D'),
    ('Unknown', 'Pesto all Genovese', 'E'),
    ('Pure Line', 'Sos jogurtowy z czosnkiem', 'UNKNOWN'),
    ('Asia Flavours', 'Sos Sriracha', 'E'),
    ('Develey', 'Sos Mayo Sriracha z chili i czosnkiem', 'D'),
    ('Heinz', 'słodki sos barbecue', 'D'),
    ('Winiary', 'Sos amerykański BBQ', 'D'),
    ('Roleski', 'Sos BBQ dark beer', 'UNKNOWN'),
    ('Italiamo', 'Sugo al pomodoro con basilico', 'A'),
    ('Mutti', 'Sauce Tomate aux légumes grillés', 'A'),
    ('Auchan', 'Passata con basilico', 'UNKNOWN'),
    ('Mondo Italiano', 'Passierte Tomaten', 'A'),
    ('Combino', 'Sauce tomate bio à la napolitaine', 'C'),
    ('Extra Line', 'Passata garlic', 'A'),
    ('Carrefour', 'Tomates basilic', 'A'),
    ('Baresa', 'Pesto alla Genovese', 'C'),
    ('Barilla', 'Pesto alla Genovese', 'E'),
    ('Carrefour', 'Pesto verde', 'D'),
    ('Go Vege', 'Pesto z tofu', 'D'),
    ('Deluxe', 'Pesto con rucola', 'D'),
    ('Heinz', 'Sauce Salade Caesar', 'E'),
    ('Sol & Mar', 'Piri-Piri', 'NOT-APPLICABLE'),
    ('Kikkoman', 'Kikkoman Sojasauce', 'E'),
    ('Mutti', 'Passierte Tomaten', 'A'),
    ('Gustobello', 'Passata', 'A')
) as d(brand, product_name, ns)
where p.country = 'PL' and p.brand = d.brand and p.product_name = d.product_name;

-- 3. NOVA classification
update products p set
  nova_classification = d.nova
from (
  values
    ('Pudliszki', 'Po Bolońsku sos do spaghetti', '3'),
    ('Culineo', 'Sos meksykański', '4'),
    ('Dawtona', 'Sos do spaghetti pomidorowo-śmietankowy', '4'),
    ('Dawtona', 'Sos Neapolitański z papryką', '4'),
    ('Dawtona', 'Sos Boloński z ziołami', '4'),
    ('Dawtona', 'Sos meksykański', '4'),
    ('Dawtona', 'Sos słodko-kwaśny z ananasem', '4'),
    ('Polskie Przetwory', 'Sos Boloński z bazylią', '4'),
    ('Międzychód', 'Sos Boloński z mięsem', '4'),
    ('Roleski', 'Sos tysiąca wysp', '4'),
    ('Heinz', 'Sos tysiąca wysp', '4'),
    ('Heinz', 'Sos Barbecue. Sos do grilla z cebulą i papryką', '4'),
    ('Fanex', 'Sos meksykański', '4'),
    ('Łowicz', 'Sos Boloński', '4'),
    ('Culineo', 'Sos boloński', '3'),
    ('Dawtona', 'Sos do pizzy z ziołami', '4'),
    ('Roleski', 'Sos pomidor + miód + limonka + nasiona chia', '4'),
    ('Pudliszki', 'Duszone pomidory o smaku smażonej cebuli i czosnku, z olejem', '4'),
    ('Fanex', 'Sos tysiąc wysp', '4'),
    ('Vital FRESH', 'Sałatka w stylu greckim', '4'),
    ('Vifon', 'Sos chili tajski słodko-pikantny', '4'),
    ('Sottile Gusto', 'Passata z czosnkiem', '3'),
    ('Sottile Gusto', 'Passata', '3'),
    ('Dawtona', 'Sos Pomidorowy do Makaronu', '4'),
    ('Międzychód', 'Sos pomidorowy', '4'),
    ('Dawtona', 'Sos Curry', '4'),
    ('Carrefour', 'Przecier pomidorowy', '4'),
    ('Culineo', 'SOS Spaghetti', '4'),
    ('Develey', 'Sos 1000 wysp', '4'),
    ('Madero', 'Sos jogurtowy z ziołami', '4'),
    ('Go Vege', 'Sos z jalapeño', '4'),
    ('Biedronka', 'Sos z chili', '4'),
    ('Vifon', 'Sos chili pikantny', '4'),
    ('Develey', 'Sos jalapeño', '4'),
    ('Dawtona', 'Sos BBQ', '4'),
    ('Madero', 'Sos BBQ z chipotle', '4'),
    ('Łowicz', 'Sos Spaghetti', '4'),
    ('Pudliszki', 'Sos Do Spaghetti Oryginalny', '3'),
    ('Dawtona', 'Passata rustica', '3'),
    ('Pudliszki', 'Przecier pomidorowy', '3'),
    ('Łowicz', 'Leczo', '3'),
    ('Roleski', 'Avocaboo!', '4'),
    ('Sottile Gusto', 'Przecier pomidorowy', '1'),
    ('Jamar', 'Passata - przecier pomidorowy klasyczny', '4'),
    ('Roleski', 'Sos do kurczaka z czosnkiem', '4'),
    ('Rolnik', 'Passata', '3'),
    ('GustoBello', 'Arrabbiata Bruschetta', '3'),
    ('Helcom', 'Dip in mexicana style', '4'),
    ('Roleski', 'Sos pomidor + czarnuszka ostry', '4'),
    ('Roleski', 'Sos pomidor + jagody goji', '3'),
    ('MW Food', 'Sauce tomate', '4'),
    ('Pudliszki', 'Bolonski', '3'),
    ('Biedronka', 'Pesto Zielone. Sos na bazie bazyli', '4'),
    ('GustoBello', 'White wine vinegar cream with pesto alla genovese', '4'),
    ('Kucharek', 'Kucharek', '4'),
    ('Roleski', 'Sos vinaigrette', '4'),
    ('Knorr', 'Sos sałatkowy paprykowo-ziołowy', '4'),
    ('Madero', 'Sos chilli pikantny', '4'),
    ('Asia Flavours', 'Sos Sriracha mayo', '4'),
    ('House of asia', 'Sos Sriracha', '4'),
    ('Asia Flavours', 'Sos Sambal Oelek', '3'),
    ('House of Asia', 'Sos z Czarnym Pieprzem', '4'),
    ('Madero', 'Sos BBQ z miodem gryczanym', '4'),
    ('Roleski', 'BBQ sos whisky', '4'),
    ('Roleski', 'Texas sos BBQ', '4'),
    ('Kotlin', 'Sos BBQ', '4'),
    ('Jamar', 'Passata klasyczna', '4'),
    ('Waldi Ben', 'Koncentrat pomidorowy 30%', '4'),
    ('Winiary', 'Spaghetti sos z pomidorów', '3'),
    ('Pingo Doce', 'Sos pomidorowy z bazylią', '4'),
    ('Podravka', 'Przecier pomidorowy z bazylią', '3'),
    ('Helcom', 'Sauce a la mexicaine', '4'),
    ('Dawtona', 'Sos pomidorowy ostry z papryczkami jalapeño', '4'),
    ('Schedro', 'Sos Chersoński', '4'),
    ('Unknown', 'Pesto all Genovese', '4'),
    ('Pure Line', 'Sos jogurtowy z czosnkiem', '4'),
    ('Asia Flavours', 'Sos Sriracha', '4'),
    ('Develey', 'Sos Mayo Sriracha z chili i czosnkiem', '4'),
    ('Heinz', 'słodki sos barbecue', '4'),
    ('Winiary', 'Sos amerykański BBQ', '4'),
    ('Roleski', 'Sos BBQ dark beer', '4'),
    ('Italiamo', 'Sugo al pomodoro con basilico', '3'),
    ('Mutti', 'Sauce Tomate aux légumes grillés', '4'),
    ('Auchan', 'Passata con basilico', '4'),
    ('Mondo Italiano', 'Passierte Tomaten', '4'),
    ('Combino', 'Sauce tomate bio à la napolitaine', '3'),
    ('Extra Line', 'Passata garlic', '3'),
    ('Carrefour', 'Tomates basilic', '4'),
    ('Baresa', 'Pesto alla Genovese', '4'),
    ('Barilla', 'Pesto alla Genovese', '4'),
    ('Carrefour', 'Pesto verde', '4'),
    ('Go Vege', 'Pesto z tofu', '4'),
    ('Deluxe', 'Pesto con rucola', '3'),
    ('Heinz', 'Sauce Salade Caesar', '4'),
    ('Sol & Mar', 'Piri-Piri', '4'),
    ('Kikkoman', 'Kikkoman Sojasauce', '3'),
    ('Mutti', 'Passierte Tomaten', '3'),
    ('Gustobello', 'Passata', '4')
) as d(brand, product_name, nova)
where p.country = 'PL' and p.brand = d.brand and p.product_name = d.product_name;

-- 0/1/4/5. Score category (concern defaults, unhealthiness, flags, confidence)
CALL score_category('Sauces');
