-- PIPELINE (Canned Goods): scoring
-- Generated: 2026-02-11

-- 2. Nutri-Score
update products p set
  nutri_score_label = d.ns
from (
  values
    ('Nasza Spiżarnia', 'Kukurydza słodka', 'B'),
    ('Dawtona', 'Kukurydza słodka', 'B'),
    ('Auchan', 'Kukurydza super słodka', 'B'),
    ('Marineo', 'Filety śledziowe w sosie pomidorowym', 'C'),
    ('Marinero', 'Płaty śledziowe smażone w zalewie octowej', 'D'),
    ('Nasza spiżarnia', 'Ogórki konserwowe', 'C'),
    ('Helcom', 'Tuńczyk kawałki w sosie własnym', 'B'),
    ('Provitus', 'Ogórki konserwowe hot chili', 'C'),
    ('Marinero', 'Łosoś Kawałki w sosie pomidorowym', 'A'),
    ('Graal', 'Tuńczyk kawałki w oleju roślinnym', 'A'),
    ('King Oscar', 'Filety z makreli w sosie pomidorowym z papryką', 'D'),
    ('Krakus', 'Ćwikła z chrzanem', 'B'),
    ('Graal', 'Sałatka z makrelą pikantna', 'C'),
    ('Mega ryba', 'Śledź w sosie pomidorowym', 'C'),
    ('Łosoś Ustka', 'Śledź w sosie pomidorowym', 'B'),
    ('EvraFish', 'Śledzie w sosie pomidorowym', 'C'),
    ('Graal', 'Tuńczyk kawałki w bulionie warzywnym', 'A'),
    ('Pudliszki', 'Pomidore krojone bez skórki w sosie pomidorowym', 'A'),
    ('Lisner', 'Tuńczyk w sosie własnym', 'A'),
    ('Nasza Spiżarnia', 'Pomidory całe', 'A'),
    ('Pudliszki', 'Fasolka po Bretońsku', 'C'),
    ('Amerigo', 'Śledź w sosie pomidorowym', 'C'),
    ('Asia Flavours', 'Jackfruit kawałki', 'A'),
    ('Krakus', 'Ogórki Korniszony', 'UNKNOWN'),
    ('Lisner', 'Tuńczyk kawałki w oleju roślinnym', 'A'),
    ('Provitus', 'Ogórki konserwowe kozackie', 'UNKNOWN'),
    ('Łowicz', 'Pomidory krojone bez skórki', 'A'),
    ('Ole!', 'Cebulka marynowana złota', 'C'),
    ('Unknown', 'Brzoskwinie połówki w lekkim syropie', 'B'),
    ('Nasza Spiżarnia', 'Mieszanka warzywna z kukuyrdzą', 'B'),
    ('Jamar', 'Mieszanka warzywna meksykańska', 'B'),
    ('Go Vege', 'Strogonow roślinny z pieczarkami', 'C'),
    ('Rolnik', 'Cebulka perłowa Premium', 'A'),
    ('Neptun', 'Tuńczyk W Wodzie', 'UNKNOWN'),
    ('EvraFish', 'Makrela po meksykańsku', 'C'),
    ('Auchan', 'Tuńczyk w kawałkach w sosie własnym', 'A'),
    ('Graal', 'Tuńczyk kawałki w sosie własnym', 'A'),
    ('Stoczek', 'Fasolka po bretońsku z dodatkiem kiełbasy', 'C'),
    ('Nasza spiżarnia', 'Brzoskwinie w syropie', 'B'),
    ('Dega', 'Fish spread with rice', 'C'),
    ('Nasza Spiżarnia', 'Pomidory Krojone', 'A'),
    ('Dawtona', 'Kukurydza gold', 'B'),
    ('Unknown', 'Buraczki zasmażane z cebulą', 'C'),
    ('Łosoś ustka', 'Paprykarz szczeciński', 'C'),
    ('Mega ryba', 'Filety z makreli w sosie pomidorowym', 'B'),
    ('Nasza Spiżarnia', 'Korniszony z chili', 'B'),
    ('Graal', 'Filety z makreli w sosie pomidorowym z suszonymi pomidorami', 'D'),
    ('Łosoś Ustka', 'Tinned Tomato Mackerel', 'D'),
    ('Graal', 'Makrela w sosie pomidorowym', 'D'),
    ('Nautica', 'Makrélafilé bőrrel paradicsomos szószban', 'C')
) as d(brand, product_name, ns)
where p.country = 'PL' and p.brand = d.brand and p.product_name = d.product_name;

-- 3. NOVA classification
update products p set
  nova_classification = d.nova
from (
  values
    ('Nasza Spiżarnia', 'Kukurydza słodka', '3'),
    ('Dawtona', 'Kukurydza słodka', '3'),
    ('Auchan', 'Kukurydza super słodka', '3'),
    ('Marineo', 'Filety śledziowe w sosie pomidorowym', '4'),
    ('Marinero', 'Płaty śledziowe smażone w zalewie octowej', '3'),
    ('Nasza spiżarnia', 'Ogórki konserwowe', '3'),
    ('Helcom', 'Tuńczyk kawałki w sosie własnym', '3'),
    ('Provitus', 'Ogórki konserwowe hot chili', '4'),
    ('Marinero', 'Łosoś Kawałki w sosie pomidorowym', '4'),
    ('Graal', 'Tuńczyk kawałki w oleju roślinnym', '3'),
    ('King Oscar', 'Filety z makreli w sosie pomidorowym z papryką', '4'),
    ('Krakus', 'Ćwikła z chrzanem', '3'),
    ('Graal', 'Sałatka z makrelą pikantna', '4'),
    ('Mega ryba', 'Śledź w sosie pomidorowym', '4'),
    ('Łosoś Ustka', 'Śledź w sosie pomidorowym', '4'),
    ('EvraFish', 'Śledzie w sosie pomidorowym', '4'),
    ('Graal', 'Tuńczyk kawałki w bulionie warzywnym', '3'),
    ('Pudliszki', 'Pomidore krojone bez skórki w sosie pomidorowym', '1'),
    ('Lisner', 'Tuńczyk w sosie własnym', '3'),
    ('Nasza Spiżarnia', 'Pomidory całe', '3'),
    ('Pudliszki', 'Fasolka po Bretońsku', '4'),
    ('Amerigo', 'Śledź w sosie pomidorowym', '4'),
    ('Asia Flavours', 'Jackfruit kawałki', '3'),
    ('Krakus', 'Ogórki Korniszony', '3'),
    ('Lisner', 'Tuńczyk kawałki w oleju roślinnym', '3'),
    ('Provitus', 'Ogórki konserwowe kozackie', '4'),
    ('Łowicz', 'Pomidory krojone bez skórki', '3'),
    ('Ole!', 'Cebulka marynowana złota', '4'),
    ('Unknown', 'Brzoskwinie połówki w lekkim syropie', '4'),
    ('Nasza Spiżarnia', 'Mieszanka warzywna z kukuyrdzą', '3'),
    ('Jamar', 'Mieszanka warzywna meksykańska', '3'),
    ('Go Vege', 'Strogonow roślinny z pieczarkami', '4'),
    ('Rolnik', 'Cebulka perłowa Premium', '3'),
    ('Neptun', 'Tuńczyk W Wodzie', '3'),
    ('EvraFish', 'Makrela po meksykańsku', '3'),
    ('Auchan', 'Tuńczyk w kawałkach w sosie własnym', '4'),
    ('Graal', 'Tuńczyk kawałki w sosie własnym', '3'),
    ('Stoczek', 'Fasolka po bretońsku z dodatkiem kiełbasy', '4'),
    ('Nasza spiżarnia', 'Brzoskwinie w syropie', '3'),
    ('Dega', 'Fish spread with rice', '4'),
    ('Nasza Spiżarnia', 'Pomidory Krojone', '3'),
    ('Dawtona', 'Kukurydza gold', '4'),
    ('Unknown', 'Buraczki zasmażane z cebulą', '4'),
    ('Łosoś ustka', 'Paprykarz szczeciński', '4'),
    ('Mega ryba', 'Filety z makreli w sosie pomidorowym', '4'),
    ('Nasza Spiżarnia', 'Korniszony z chili', '3'),
    ('Graal', 'Filety z makreli w sosie pomidorowym z suszonymi pomidorami', '4'),
    ('Łosoś Ustka', 'Tinned Tomato Mackerel', '4'),
    ('Graal', 'Makrela w sosie pomidorowym', '4'),
    ('Nautica', 'Makrélafilé bőrrel paradicsomos szószban', '4')
) as d(brand, product_name, nova)
where p.country = 'PL' and p.brand = d.brand and p.product_name = d.product_name;

-- 0/1/4/5. Score category (concern defaults, unhealthiness, flags, confidence)
CALL score_category('Canned Goods');
