-- PIPELINE (Snacks): scoring
-- Generated: 2026-02-09

-- 2. Nutri-Score
update products p set
  nutri_score_label = d.ns
from (
  values
    ('Pano', 'Wafle Kukurydziane z Kaszą jaglaną i Pieprzem', 'B'),
    ('Go Active', 'Baton wysokobiałkowy Peanut Butter', 'C'),
    ('Go Active', 'Baton białkowy malinowy', 'C'),
    ('Sonko', 'Wafle ryżowe w czekoladzie mlecznej', 'E'),
    ('Kupiec', 'Wafle ryżowe naturalne', 'B'),
    ('Bakalland', 'Ba! żurawina', 'D'),
    ('Vital Fresh', 'Surówka Colesław z białej kapusty', 'A'),
    ('Lay''s', 'Oven Baked Krakersy wielozbożowe', 'D'),
    ('Pano', 'Wafle mini, zbożowe', 'B'),
    ('Dobra Kaloria', 'Mini batoniki z nerkowców à la tarta malinowa', 'D'),
    ('Lubella', 'Paluszki z solą', 'E'),
    ('Dobra Kaloria', 'Wysokobiałkowy Baton Krem Orzechowy Z Nutą Karmelu', 'C'),
    ('Brześć', 'Słomka ptysiowa', 'D'),
    ('Go On', 'Sante Baton Proteinowy Go On Kakaowy', 'NOT-APPLICABLE'),
    ('Lajkonik', 'Paluszki extra cienkie', 'E'),
    ('Wafle Dzik', 'Kukurydziane - ser', 'D'),
    ('Sante', 'Crunchy Cranberry & Raspberry - Sante', 'E'),
    ('Miami', 'Paleczki', 'B'),
    ('Aksam', 'Beskidzkie paluszki o smaku sera i cebulki', 'E'),
    ('Go On Nutrition', 'Protein 33% Caramel', 'NOT-APPLICABLE'),
    ('Lajkonik', 'Salted cracker', 'D'),
    ('Lorenz', 'Chrupki Curly', 'D'),
    ('Lajkonik', 'prezel', 'B'),
    ('Lajkonik', 'Krakersy mini', 'D'),
    ('San', 'San bieszczadzkie suchary', 'C'),
    ('Sante', 'Vitamin coconut bar', 'NOT-APPLICABLE'),
    ('Lajkonik', 'Junior Safari', 'D'),
    ('Dobra Kaloria', 'Kokos & Orzech', 'D'),
    ('Lajkonik', 'Drobne pieczywo o smaku waniliowym', 'B'),
    ('Top', 'Paluszki solone', 'D'),
    ('Baron', 'Protein BarMax Caramel', 'NOT-APPLICABLE'),
    ('Go On', 'Keto Bar', 'NOT-APPLICABLE'),
    ('Top', 'popcorn solony', 'E'),
    ('Oshee', 'Raspberry & Almond High Protein Bar PROMO', 'NOT-APPLICABLE'),
    ('lajkonik', 'dobry chrup', 'D'),
    ('Lajkonik', 'Precelki chrupkie', 'E'),
    ('Be raw', 'Energy Raspberry', 'NOT-APPLICABLE'),
    ('Go Active', 'Baton Proteinowy Smak Waniliowy 50%', 'NOT-APPLICABLE'),
    ('As Babuni', 'Chrup Asy Wafle Paprykowe', 'E'),
    ('Go Active', 'Baton wysokobiałkowy z pistacjami', 'NOT-APPLICABLE'),
    ('Góralki', 'Góralki mleczne', 'E'),
    ('Bob Snail', 'Jabłkowo-truskawkowe przekąski', 'C'),
    ('Tastino', 'Małe Wafle Kukurydziane O Smaku Pizzy', 'C'),
    ('Unknown', 'Protein vanillia raspberry', 'NOT-APPLICABLE'),
    ('Go Active', 'Baton wysokobiałkowy z migdałami i kokosem', 'NOT-APPLICABLE'),
    ('7 Days', 'Croissant with Cocoa Filling', 'E'),
    ('Vitanella', 'Barony', 'D'),
    ('Unknown', 'Baton Vitanella z migdałami, żurawiną i orzeszkami ziemnymi', 'D'),
    ('Tutti', 'Batonik twarogowy Tutti w polewie czekoladowej', 'E'),
    ('7 Days', '7 Days', 'E'),
    ('Maretti', 'Bruschette Chips Pizza Flavour', 'D'),
    ('Tastino', 'Wafle Kukurydziane', 'C'),
    ('Pilos', 'Barretta al quark gusto Nocciola', 'E'),
    ('Aviko', 'Frytki karbowane Zig Zag', 'A'),
    ('7 Days', 'family', 'UNKNOWN'),
    ('Milka', 'Cake & Chock', 'E'),
    ('Wasa', 'Lekkie 7 Ziaren', 'B'),
    -- batch 2
    ('Sante', 'Crunchy Cranberry & Raspberry - Sante', 'D')  -- high sugar cereal bar
) as d(brand, product_name, ns)
where p.country = 'PL' and p.brand = d.brand and p.product_name = d.product_name;

-- 3. NOVA classification
update products p set
  nova_classification = d.nova
from (
  values
    ('Pano', 'Wafle Kukurydziane z Kaszą jaglaną i Pieprzem', '3'),
    ('Go Active', 'Baton wysokobiałkowy Peanut Butter', '4'),
    ('Go Active', 'Baton białkowy malinowy', '4'),
    ('Sonko', 'Wafle ryżowe w czekoladzie mlecznej', '4'),
    ('Kupiec', 'Wafle ryżowe naturalne', '1'),
    ('Bakalland', 'Ba! żurawina', '4'),
    ('Vital Fresh', 'Surówka Colesław z białej kapusty', '4'),
    ('Lay''s', 'Oven Baked Krakersy wielozbożowe', '4'),
    ('Pano', 'Wafle mini, zbożowe', '3'),
    ('Dobra Kaloria', 'Mini batoniki z nerkowców à la tarta malinowa', '4'),
    ('Lubella', 'Paluszki z solą', '3'),
    ('Dobra Kaloria', 'Wysokobiałkowy Baton Krem Orzechowy Z Nutą Karmelu', '4'),
    ('Brześć', 'Słomka ptysiowa', '3'),
    ('Go On', 'Sante Baton Proteinowy Go On Kakaowy', '4'),
    ('Lajkonik', 'Paluszki extra cienkie', '3'),
    ('Wafle Dzik', 'Kukurydziane - ser', '4'),
    ('Sante', 'Crunchy Cranberry & Raspberry - Sante', '4'),
    ('Miami', 'Paleczki', '1'),
    ('Aksam', 'Beskidzkie paluszki o smaku sera i cebulki', '4'),
    ('Go On Nutrition', 'Protein 33% Caramel', '4'),
    ('Lajkonik', 'Salted cracker', '4'),
    ('Lorenz', 'Chrupki Curly', '4'),
    ('Lajkonik', 'prezel', '3'),
    ('Lajkonik', 'Krakersy mini', '4'),
    ('San', 'San bieszczadzkie suchary', '4'),
    ('Sante', 'Vitamin coconut bar', '4'),
    ('Lajkonik', 'Junior Safari', '4'),
    ('Dobra Kaloria', 'Kokos & Orzech', '3'),
    ('Lajkonik', 'Drobne pieczywo o smaku waniliowym', '4'),
    ('Top', 'Paluszki solone', '4'),
    ('Baron', 'Protein BarMax Caramel', '4'),
    ('Go On', 'Keto Bar', '4'),
    ('Top', 'popcorn solony', '4'),
    ('Oshee', 'Raspberry & Almond High Protein Bar PROMO', '4'),
    ('lajkonik', 'dobry chrup', '4'),
    ('Lajkonik', 'Precelki chrupkie', '3'),
    ('Be raw', 'Energy Raspberry', '4'),
    ('Go Active', 'Baton Proteinowy Smak Waniliowy 50%', '4'),
    ('As Babuni', 'Chrup Asy Wafle Paprykowe', '4'),
    ('Go Active', 'Baton wysokobiałkowy z pistacjami', '4'),
    ('Góralki', 'Góralki mleczne', '4'),
    ('Bob Snail', 'Jabłkowo-truskawkowe przekąski', '3'),
    ('Tastino', 'Małe Wafle Kukurydziane O Smaku Pizzy', '4'),
    ('Unknown', 'Protein vanillia raspberry', '4'),
    ('Go Active', 'Baton wysokobiałkowy z migdałami i kokosem', '4'),
    ('7 Days', 'Croissant with Cocoa Filling', '4'),
    ('Vitanella', 'Barony', '4'),
    ('Unknown', 'Baton Vitanella z migdałami, żurawiną i orzeszkami ziemnymi', '4'),
    ('Tutti', 'Batonik twarogowy Tutti w polewie czekoladowej', '4'),
    ('7 Days', '7 Days', '4'),
    ('Maretti', 'Bruschette Chips Pizza Flavour', '4'),
    ('Tastino', 'Wafle Kukurydziane', '4'),
    ('Pilos', 'Barretta al quark gusto Nocciola', '4'),
    ('Aviko', 'Frytki karbowane Zig Zag', '4'),
    ('7 Days', 'family', '4'),
    ('Milka', 'Cake & Chock', '4'),
    ('Wasa', 'Lekkie 7 Ziaren', '3'),
    -- batch 2
    ('Sante', 'Crunchy Cranberry & Raspberry - Sante', '4')  -- coated cereal bar
) as d(brand, product_name, nova)
where p.country = 'PL' and p.brand = d.brand and p.product_name = d.product_name;

-- 0/1/4/5. Score category (concern defaults, unhealthiness, flags, confidence)
CALL score_category('Snacks');
