-- 20260207_000_baseline.sql
-- Purpose:
-- 1) Ensure primary keys auto-increment (identity) for products + servings
-- 2) Ensure uniqueness for UPSERT on (country, brand, product_name)
-- 3) Ensure pipeline-required columns exist
-- 4) Add performance indexes

-- 0) Safety: schema
set search_path = public;

-- 1) Ensure products.product_id is identity (auto-increment)
do $$
begin
  -- add identity only if not already identity
  if not exists (
    select 1
    from information_schema.columns
    where table_schema='public'
      and table_name='products'
      and column_name='product_id'
      and is_identity='YES'
  ) then
    execute 'alter table public.products alter column product_id add generated by default as identity';
  end if;
end $$;

-- Sync products identity sequence to max(product_id)
select setval(
  pg_get_serial_sequence('public.products','product_id'),
  coalesce((select max(product_id) from public.products), 1)
);

-- 2) Ensure servings.serving_id is identity (auto-increment)
do $$
begin
  if not exists (
    select 1
    from information_schema.columns
    where table_schema='public'
      and table_name='servings'
      and column_name='serving_id'
      and is_identity='YES'
  ) then
    execute 'alter table public.servings alter column serving_id add generated by default as identity';
  end if;
end $$;

-- Sync servings identity sequence to max(serving_id)
select setval(
  pg_get_serial_sequence('public.servings','serving_id'),
  coalesce((select max(serving_id) from public.servings), 1)
);

-- 3) Ensure products has deprecation flags (used to hide generic reference rows from rankings)
alter table public.products
  add column if not exists is_deprecated boolean default false,
  add column if not exists deprecated_reason text;

-- 4) Ensure servings has serving metadata columns
alter table public.servings
  add column if not exists serving_basis text,
  add column if not exists serving_amount_g_ml numeric;

-- 5) Ensure scores has v2 columns
alter table public.scores
  add column if not exists data_completeness_pct numeric,
  add column if not exists confidence text,
  add column if not exists personal_unhealthiness_balanced numeric,
  add column if not exists personal_unhealthiness_low_salt numeric,
  add column if not exists personal_unhealthiness_low_sugar numeric;

-- 6) Create UNIQUE index for UPSERT key (country, brand, product_name)
create unique index if not exists products_country_brand_name_uniq
on public.products (country, brand, product_name);

-- 7) Add useful indexes for joins (performance as dataset grows)
create index if not exists servings_product_id_idx
on public.servings (product_id);

create index if not exists nutrition_facts_product_serving_idx
on public.nutrition_facts (product_id, serving_id);

create index if not exists scores_product_id_idx
on public.scores (product_id);

create index if not exists ingredients_product_id_idx
on public.ingredients (product_id);
